SET IDENTITY_INSERT [dbo].[Movies] ON
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (1, N'Forrest Gump', 3, N'2017-11-04 00:00:00', N'1994-09-30 00:00:00', N'Tom Hanks, Sally Field', N'
JFK, LBJ, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (3, N'The Wolf of Wall Street', 9, N'2017-11-04 00:00:00', N'2013-01-02 00:00:00', N' Leonardo DiCaprio, Jonah Hill, Margot Robbie', N'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (4, N'The Notebook', 2, N'2017-11-04 00:00:00', N'2004-08-05 00:00:00', N'Ryan Gosling, Rachel McAdams', N'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (5, N'Frozen', 7, N'2017-11-04 00:00:00', N'2013-11-28 00:00:00', N' Kristen Bell, Idina Menzel, Jonathan Groff ', N'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister, Anna, teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (6, N'Inception', 6, N'2017-11-04 00:00:00', N'2010-07-22 00:00:00', N'NULL Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page', N'A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (7, N'Gladiator ', 4, N'2017-11-04 00:00:00', N'2000-05-18 00:00:00', N' Russell Crowe, Joaquin Phoenix, Connie Nielsen', N'When a Roman General is betrayed, and his family murdered by an emperor''s corrupt son, he comes to Rome as a gladiator to seek revenge. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (8, N'The Hangover', 1, N'2017-11-04 00:00:00', N'2009-07-30 00:00:00', N' Zach Galifianakis, Bradley Cooper, Justin Bartha', N'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (9, N'Scream', 5, N'2017-11-04 00:00:00', N'1996-12-20 00:00:00', N' Neve Campbell, Courteney Cox, David Arquette ', N'A year after the murder of her mother, a teenage girl is terrorized by a new killer, who targets the girl and her friends by using horror films as part of a deadly game. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (10, N'Harry Potter and the Sorcerer''s Stone', 8, N'2017-11-04 00:00:00', N'2001-11-29 00:00:00', N'Daniel Radcliffe, Rupert Grint, Richard Harris ', N'Rescued from the outrageous neglect of his aunt and uncle, a young boy with a great destiny proves his worth while attending Hogwarts School of Witchcraft and Wizardry. ')
INSERT INTO [dbo].[Movies] ([ID], [movieName], [genreID], [dateAdded], [releaseDate], [actors], [summary]) VALUES (11, N'Fifty Shades Darker', 10, N'2017-11-04 00:00:00', N'2017-02-09 00:00:00', N' Dakota Johnson, Jamie Dornan, Eric Johnson', N'While Christian wrestles with his inner demons, Anastasia must confront the anger and envy of the women who came before her. ')
SET IDENTITY_INSERT [dbo].[Movies] OFF
